// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9l5OgzcQMwFHY-nm3h3uF7q6j4KPMrtM',
    appId: '1:627476252828:web:64f300a20a1e53790b4559',
    messagingSenderId: '627476252828',
    projectId: 'suchi-3b304',
    authDomain: 'suchi-3b304.firebaseapp.com',
    storageBucket: 'suchi-3b304.appspot.com',
    measurementId: 'G-0PLZTL77KX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk5YCludoGgxzodGFJshR726QGWJM0TPQ',
    appId: '1:627476252828:android:0ea4949f369396d90b4559',
    messagingSenderId: '627476252828',
    projectId: 'suchi-3b304',
    storageBucket: 'suchi-3b304.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPRdrWtxw-Cm7v24eePogaKEwpRnJiUGE',
    appId: '1:627476252828:ios:787fe2b90cc37c3a0b4559',
    messagingSenderId: '627476252828',
    projectId: 'suchi-3b304',
    storageBucket: 'suchi-3b304.appspot.com',
    iosClientId: '627476252828-25f82p24mqvvbm593bugmu75l72goctg.apps.googleusercontent.com',
    iosBundleId: 'com.example.souchi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPRdrWtxw-Cm7v24eePogaKEwpRnJiUGE',
    appId: '1:627476252828:ios:787fe2b90cc37c3a0b4559',
    messagingSenderId: '627476252828',
    projectId: 'suchi-3b304',
    storageBucket: 'suchi-3b304.appspot.com',
    iosClientId: '627476252828-25f82p24mqvvbm593bugmu75l72goctg.apps.googleusercontent.com',
    iosBundleId: 'com.example.souchi',
  );
}
